apiVersion : apps/v1
kind: Deployment
metadata:
  name: "buggerkubernetes-52d2"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "buggerkubernetes-52d2"
  template:
    metadata:
      labels:
        app: "buggerkubernetes-52d2"
    spec:
      containers:
        - name: "buggerkubernetes-52d2"
          image: "buggercountertest.azurecr.io/buggerkubernetes"
          ports:
          - containerPort: 5002