apiVersion: v1
kind: Service
metadata:
    name: "buggerkubernetes-52d2"
    labels:
        app: "buggerkubernetes-52d2"
spec:
    type: LoadBalancer
    ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
      name: http
    selector:
        app: "buggerkubernetes-52d2"